version: '3.4'

services:

  postgre-db:
    image: postgres:13
    container_name: postgre-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:7.1
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    volumes:
      - ./postgresql/pgadmin:/var/lib/pgadmin